### ISSUE TITLE
devel versions not installing after `nomad::pack(".")`

### ISSUE THREAD

**Issue by thibautjombart** [reconhub/nomad#1]
Using the config files attached, and after `nomad::pack("test1")`, I get:

```
> install.packages("rfiglet", repos = "file:///home/thibaut/temp/test1")
Installing package into ‘/usr/local/lib/R/site-library’
(as ‘lib’ is unspecified)
Warning message:
package ‘rfiglet’ is not available (for R version 3.4.0) 
> 
```
while `install.packages("abc", repos = "file:///home/thibaut/temp/test1")` works. The folder `test1/drat/src` seems to contain relevant files. We trying to install from the source, it seems dependencies are missing:
```
> install.packages("drat/src/contrib/rfiglet_0.1.0.tar.gz", repos = NULL)
Installing package into ‘/usr/local/lib/R/site-library’
(as ‘lib’ is unspecified)
ERROR: dependency ‘rappdirs’ is not available for package ‘rfiglet’
* removing ‘/usr/local/lib/R/site-library/rfiglet’
Warning message:
In install.packages("drat/src/contrib/rfiglet_0.1.0.tar.gz", repos = NULL) :
  installation of package ‘drat/src/contrib/rfiglet_0.1.0.tar.gz’ had non-zero exit status
```
It looks like it should have been install since it is listed in Imports:
https://github.com/richfitz/rfiglet/blob/master/DESCRIPTION#L9

[test1.zip](https://github.com/reconhub/nomad/files/1092391/test1.zip)

**Comment by richfitz** [comment]
You need to add `rfiglet` to the `package_list.txt` file

**Comment by thibautjombart** [comment]
OK thanks, fixes it. Would it make sense for the general case to add packages listed in `package_sources` automatically to `package_list`? Probably worth documenting anyhow.
